global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: alert-ingestion
    metrics_path: /metrics
    dns_sd_configs:
      - names: ["alert-ingestion"]
        type: A
        port: 8001

  - job_name: incident-management
    metrics_path: /metrics
    dns_sd_configs:
      - names: ["incident-management"]
        type: A
        port: 8002

  - job_name: oncall
    metrics_path: /metrics
    static_configs:
      - targets: ["oncall-service:8003"]

  - job_name: notification
    metrics_path: /metrics
    static_configs:
      - targets: ["notification-service:8004"]

  - job_name: gateway
    metrics_path: /metrics
    static_configs:
      - targets: ["gateway:8000"]

  - job_name: monitoring
    metrics_path: /metrics
    static_configs:
      - targets: ["monitoring:8000"]
