name: gateway

on:
  workflow_dispatch:
  push:
    paths:
      - "gateway-service/**"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "gateway-service/**"
      - ".github/workflows/**"

jobs:
  build:
    uses: ./.github/workflows/_docker-build.yml
    with:
      name: gateway
      context: ./gateway-service
      dockerfile: ./gateway-service/Dockerfile
      tag: ims/gateway:ci
      smoke: true
      container_port: 8000
      health_path: /health
